'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OOP_Prac18.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 109 Spencer Dr, Paisley PA2 0TW, UK
        '''3 Nellington Rd, Rusthall, Tunbridge Wells TN4 8SH, UK
        '''8 Dorsett Rd Terrace, Wednesbury WS10 8TP, UK
        '''32 Denver Rd, Fforest-fach, Swansea SA5 4DA, UK
        '''11 Roding Ln S, Ilford, Woodford Green IG8 8EY, UK
        '''103 Station Rd, Burnham-on-Crouch CM0 8HQ, UK
        '''19 Home Meadow, Welwyn Garden City AL7 3BA, UK
        '''5 Auchraw Terrace, Lochearnhead FK19 8PS, UK
        '''43 Park Ln, Shiremoor, Newcastle upon Tyne NE27 0TG, UK
        '''4 Murray Ct, Balmullo, St Andrews KY16 0AT, UK
        '''The Squires House, 2 Gamb [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property addresslist() As String
            Get
                Return ResourceManager.GetString("addresslist", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Mercy Grosso
        '''Luisa Mccaffery
        '''Sudie Montalbo
        '''Ruth Krum
        '''Maragaret Gaiser
        '''Celestine Shue
        '''Booker Bauer
        '''Deena Capozzoli
        '''Shanae Ramon
        '''Lara Leff
        '''Marybelle Ketron
        '''Wendy Haughton
        '''Velva Hickerson
        '''Danyelle Hurtt
        '''Evon Kish
        '''Socorro Rux
        '''Veda Woodie
        '''Suzanne Daigle
        '''Herman Michalik
        '''Ute Islam
        '''Sibyl Sheilds
        '''Gino Dehner
        '''Ruthie Vedder
        '''Helene Trivette
        '''Santina Carty
        '''Raelene Lovelady
        '''Hyon Bibby
        '''Kaitlyn Gaxiola
        '''Young Stmarie
        '''Shaunda Galindez
        '''Annetta Eichman
        '''Fidel Lightsey
        '''Yetta Foronda
        '''Luana Linsey        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property namelist() As String
            Get
                Return ResourceManager.GetString("namelist", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
